### ISSUE TITLE
Trying to publish to evidence repository without evaluated criterion leads to errors

### ISSUE THREAD

**Issue by liammulh** [ClinGen/VCI-transformation#8]
@bryanwulf said "looks like the absence of at least one evaluation causes an error/failure in the SEPIO transformation service (it’s attempting to retrieve the “evaluations” key and only catching IndexError exceptions - not KeyError)".

Conversation from Slack:

>Liam Mulhall
Hey Bryan. I was testing out a fix, and when I tried to publish https://curation-test.clinicalgenome.org/variant-central/2cd7dce9-4177-4a09-9dc8-d724e67d7a9d/interpretation/1154291b-0803-4f73-9b7f-12d53e92dab3 to the evidence repository, I saw these errors in the console:
```
xhr.js:177     GET https://rq6q71bfy4.execute-api.us-west-2.amazonaws.com/ptest/messaging/publish/7be58690-6bdb-4bfb-8a89-61fac7c27dc2 400
publish.js:176 Internal data retrieval error: Error: Request failed with status code 400
publish.js:562 Interpretation publication error = : Error: Request failed with status code 400
Mark thought it would be a good idea to loop you in. It doesn't seem to be happening on dev or other instances.
```

>Bryan Wulf
just tried to take a look at the interpretation… were you curating as an individual?

>Liam Mulhall
As opposed to having an affiliation?

>Bryan Wulf
yeah

>Liam Mulhall
I was curating as part of the Hearing Loss affiliation

>Bryan Wulf
ah, ok… wasn’t seeing anything indicating an affiliation :stuck_out_tongue:
looks like generating ClinVar submission data fails as well… looking at logs… I’m suspicious of the absence of any evaluated criteria…

>Liam Mulhall
The lack of evaluated criteria might cause the errors?

>Bryan Wulf
yeah… don’t recall if at least one evaluation is expected by the transformation service

>Liam Mulhall
Ah, gotcha. So it could be a corner case

>Bryan Wulf
not seeing anything useful in the transformation service logs (group is /aws/lambda/sepio-transform), so I’m attempting to run the transformation process locally against the interpretation saved in the approved snapshot

>Bryan Wulf
looks like the absence of at least one evaluation causes an error/failure in the SEPIO transformation service (it’s attempting to retrieve the “evaluations” key and only catching IndexError exceptions - not KeyError)
try evaluating a criteria and redoing the approval process (save, provision and approve)

>Liam Mulhall
Okay, will do

>Bryan Wulf
if you’d like to report/record the issue (I’m thinking I could probably fix it this week or next - with or without a ticket), here’s the appropriate repo: https://github.com/ClinGen/VCI-transformation

>Liam Mulhall
I evaluated some criteria, but I am still seeing the errors when I try to publish
I will open an issue
It could be I'm doing something wrong

>Bryan Wulf
I was able to generate ClinVar submission data on the most recent approved snapshot

>Liam Mulhall
Ah, okay good

**Comment by bryanwulf** [comment]
A fix for this issue has been implemented and deployed: #9
